### ISSUE TITLE
Not compatible with Colored Icon Kit mod

### ISSUE THREAD

**Issue by BWGucio** [hiimjasmine00/BetterIconRandomizer#1]
So I was messing around with this mod and noticed that when you got the Colored Icon Kit mod downloaded, it's doing this:

![image](https://github.com/hiimjustin000/BetterIconRandomizer/assets/99192838/51bf5b27-ef53-4087-83ea-6e95ac6c4dc0)

I tried redownloading both of them and it doesn't work
I don't know if it's a bug or something, but I wanted to post it here, so maybe it will get fixed

**Comment by sofabeddd** [comment]
hello, colored icon kit dev, this is an april fools thing

**Comment by BWGucio** [comment]
> hello, colored icon kit dev, this is an april fools thing

My god, I'm so stupid
Thanks for the reply
