### ISSUE TITLE
Various crashes on mobile related to pause submenus

### ISSUE THREAD

**Issue by FRBFStudios** [hiimjasmine00/BetterIconRandomizer#2]
On android, I've encountered multiple crashes with this mod occuring after I open and close a submenu of the pause menu such as the Prism menu overlay or the "more settings" menu. It seems to become more stable when I use pause mode 2, but it still crashes every now and then. Idk if this is a known issue but I still reported it. (Also the quest collection sound gets delayed until I unpause but that is definitely a known issue).

**Comment by hiimjasmine00** [comment]
Send the crash log.

**Comment by FRBFStudios** [comment]
I'm trying but for some reason my phone prevents me from attaching the crashlog here :( I'll try to upload it to OneDrive and share the crashlog from my computer later, but you should be able to easily replicate the crash by pausing (on android), clicking on the settings icon, clicking on the settings button in the settings menu again and then closing both menus.

**Comment by FRBFStudios** [comment]
[Crash 2024-04-28 06.10.45.dmp](https://github.com/hiimjustin000/BetterIconRandomizer/files/15142066/Crash.2024-04-28.06.10.45.dmp)

there you go

**Comment by hiimjasmine00** [comment]
Forward this issue to https://github.com/eloh-mrow/death-tracker or the [Geode SDK Discord server](https://discord.gg/9e43WMKzhp)
